//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto2.WSp2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://proyecto2.org/", ConfigurationName="WSp2.proyectoWSSoap")]
    public interface proyectoWSSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://proyecto2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/HelloWorld", ReplyAction="*")]
        Proyecto2.WSp2.HelloWorldResponse HelloWorld(Proyecto2.WSp2.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/insertarMatriz", ReplyAction="*")]
        void insertarMatriz(int x, int y, double costoV, int tiempoV);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/graficarMatriz", ReplyAction="*")]
        void graficarMatriz();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/limpiarWS", ReplyAction="*")]
        void limpiarWS();
        
        // CODEGEN: Generating message contract since element name nomDes from namespace http://proyecto2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/insertarAb", ReplyAction="*")]
        Proyecto2.WSp2.insertarAbResponse insertarAb(Proyecto2.WSp2.insertarAbRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/graficarAb", ReplyAction="*")]
        void graficarAb();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/graficarAbDest", ReplyAction="*")]
        void graficarAbDest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/graficarAbOrig", ReplyAction="*")]
        void graficarAbOrig();
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://proyecto2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/IngresarHash", ReplyAction="*")]
        Proyecto2.WSp2.IngresarHashResponse IngresarHash(Proyecto2.WSp2.IngresarHashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/graficarHash", ReplyAction="*")]
        void graficarHash();
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://proyecto2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/buscarClaveHash", ReplyAction="*")]
        Proyecto2.WSp2.buscarClaveHashResponse buscarClaveHash(Proyecto2.WSp2.buscarClaveHashRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/insertarVuelo", ReplyAction="*")]
        void insertarVuelo(int clave, int cod);
        
        // CODEGEN: Generating message contract since element name nomDes from namespace http://proyecto2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/insertarAbdm", ReplyAction="*")]
        Proyecto2.WSp2.insertarAbdmResponse insertarAbdm(Proyecto2.WSp2.insertarAbdmRequest request);
        
        // CODEGEN: Generating message contract since element name nomDes from namespace http://proyecto2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/insertarAbom", ReplyAction="*")]
        Proyecto2.WSp2.insertarAbomResponse insertarAbom(Proyecto2.WSp2.insertarAbomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/busquedaABD", ReplyAction="*")]
        bool busquedaABD(int numero);
        
        // CODEGEN: Generating message contract since element name recorrerColResult from namespace http://proyecto2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/recorrerCol", ReplyAction="*")]
        Proyecto2.WSp2.recorrerColResponse recorrerCol(Proyecto2.WSp2.recorrerColRequest request);
        
        // CODEGEN: Generating message contract since element name recorrerFilResult from namespace http://proyecto2.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/recorrerFil", ReplyAction="*")]
        Proyecto2.WSp2.recorrerFilResponse recorrerFil(Proyecto2.WSp2.recorrerFilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/eliminarMatriz", ReplyAction="*")]
        void eliminarMatriz(int PrimerPais, int SegundoPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/modificarMatriz", ReplyAction="*")]
        void modificarMatriz(int PrimerPais, int SegundoPais, double costo, int tiempo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://proyecto2.org/graficarGrafo", ReplyAction="*")]
        void graficarGrafo();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Proyecto2.WSp2.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Proyecto2.WSp2.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarAbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarAb", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.insertarAbRequestBody Body;
        
        public insertarAbRequest() {
        }
        
        public insertarAbRequest(Proyecto2.WSp2.insertarAbRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class insertarAbRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codDes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomDes;
        
        public insertarAbRequestBody() {
        }
        
        public insertarAbRequestBody(int codDes, string nomDes) {
            this.codDes = codDes;
            this.nomDes = nomDes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarAbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarAbResponse", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.insertarAbResponseBody Body;
        
        public insertarAbResponse() {
        }
        
        public insertarAbResponse(Proyecto2.WSp2.insertarAbResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarAbResponseBody {
        
        public insertarAbResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarHashRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarHash", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.IngresarHashRequestBody Body;
        
        public IngresarHashRequest() {
        }
        
        public IngresarHashRequest(Proyecto2.WSp2.IngresarHashRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class IngresarHashRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int reser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public float cost;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float time;
        
        public IngresarHashRequestBody() {
        }
        
        public IngresarHashRequestBody(string nombre, int reser, float cost, float time) {
            this.nombre = nombre;
            this.reser = reser;
            this.cost = cost;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IngresarHashResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IngresarHashResponse", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.IngresarHashResponseBody Body;
        
        public IngresarHashResponse() {
        }
        
        public IngresarHashResponse(Proyecto2.WSp2.IngresarHashResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IngresarHashResponseBody {
        
        public IngresarHashResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarClaveHashRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarClaveHash", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.buscarClaveHashRequestBody Body;
        
        public buscarClaveHashRequest() {
        }
        
        public buscarClaveHashRequest(Proyecto2.WSp2.buscarClaveHashRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class buscarClaveHashRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        public buscarClaveHashRequestBody() {
        }
        
        public buscarClaveHashRequestBody(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarClaveHashResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarClaveHashResponse", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.buscarClaveHashResponseBody Body;
        
        public buscarClaveHashResponse() {
        }
        
        public buscarClaveHashResponse(Proyecto2.WSp2.buscarClaveHashResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class buscarClaveHashResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int buscarClaveHashResult;
        
        public buscarClaveHashResponseBody() {
        }
        
        public buscarClaveHashResponseBody(int buscarClaveHashResult) {
            this.buscarClaveHashResult = buscarClaveHashResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarAbdmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarAbdm", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.insertarAbdmRequestBody Body;
        
        public insertarAbdmRequest() {
        }
        
        public insertarAbdmRequest(Proyecto2.WSp2.insertarAbdmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class insertarAbdmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codDes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomDes;
        
        public insertarAbdmRequestBody() {
        }
        
        public insertarAbdmRequestBody(int codDes, string nomDes) {
            this.codDes = codDes;
            this.nomDes = nomDes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarAbdmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarAbdmResponse", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.insertarAbdmResponseBody Body;
        
        public insertarAbdmResponse() {
        }
        
        public insertarAbdmResponse(Proyecto2.WSp2.insertarAbdmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarAbdmResponseBody {
        
        public insertarAbdmResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarAbomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarAbom", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.insertarAbomRequestBody Body;
        
        public insertarAbomRequest() {
        }
        
        public insertarAbomRequest(Proyecto2.WSp2.insertarAbomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class insertarAbomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int codDes;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nomDes;
        
        public insertarAbomRequestBody() {
        }
        
        public insertarAbomRequestBody(int codDes, string nomDes) {
            this.codDes = codDes;
            this.nomDes = nomDes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarAbomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarAbomResponse", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.insertarAbomResponseBody Body;
        
        public insertarAbomResponse() {
        }
        
        public insertarAbomResponse(Proyecto2.WSp2.insertarAbomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertarAbomResponseBody {
        
        public insertarAbomResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recorrerColRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recorrerCol", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.recorrerColRequestBody Body;
        
        public recorrerColRequest() {
        }
        
        public recorrerColRequest(Proyecto2.WSp2.recorrerColRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class recorrerColRequestBody {
        
        public recorrerColRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recorrerColResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recorrerColResponse", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.recorrerColResponseBody Body;
        
        public recorrerColResponse() {
        }
        
        public recorrerColResponse(Proyecto2.WSp2.recorrerColResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class recorrerColResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recorrerColResult;
        
        public recorrerColResponseBody() {
        }
        
        public recorrerColResponseBody(string recorrerColResult) {
            this.recorrerColResult = recorrerColResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recorrerFilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recorrerFil", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.recorrerFilRequestBody Body;
        
        public recorrerFilRequest() {
        }
        
        public recorrerFilRequest(Proyecto2.WSp2.recorrerFilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class recorrerFilRequestBody {
        
        public recorrerFilRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recorrerFilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="recorrerFilResponse", Namespace="http://proyecto2.org/", Order=0)]
        public Proyecto2.WSp2.recorrerFilResponseBody Body;
        
        public recorrerFilResponse() {
        }
        
        public recorrerFilResponse(Proyecto2.WSp2.recorrerFilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://proyecto2.org/")]
    public partial class recorrerFilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string recorrerFilResult;
        
        public recorrerFilResponseBody() {
        }
        
        public recorrerFilResponseBody(string recorrerFilResult) {
            this.recorrerFilResult = recorrerFilResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface proyectoWSSoapChannel : Proyecto2.WSp2.proyectoWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class proyectoWSSoapClient : System.ServiceModel.ClientBase<Proyecto2.WSp2.proyectoWSSoap>, Proyecto2.WSp2.proyectoWSSoap {
        
        public proyectoWSSoapClient() {
        }
        
        public proyectoWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public proyectoWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proyectoWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public proyectoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.WSp2.HelloWorldResponse Proyecto2.WSp2.proyectoWSSoap.HelloWorld(Proyecto2.WSp2.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Proyecto2.WSp2.HelloWorldRequest inValue = new Proyecto2.WSp2.HelloWorldRequest();
            inValue.Body = new Proyecto2.WSp2.HelloWorldRequestBody();
            Proyecto2.WSp2.HelloWorldResponse retVal = ((Proyecto2.WSp2.proyectoWSSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public void insertarMatriz(int x, int y, double costoV, int tiempoV) {
            base.Channel.insertarMatriz(x, y, costoV, tiempoV);
        }
        
        public void graficarMatriz() {
            base.Channel.graficarMatriz();
        }
        
        public void limpiarWS() {
            base.Channel.limpiarWS();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.WSp2.insertarAbResponse Proyecto2.WSp2.proyectoWSSoap.insertarAb(Proyecto2.WSp2.insertarAbRequest request) {
            return base.Channel.insertarAb(request);
        }
        
        public void insertarAb(int codDes, string nomDes) {
            Proyecto2.WSp2.insertarAbRequest inValue = new Proyecto2.WSp2.insertarAbRequest();
            inValue.Body = new Proyecto2.WSp2.insertarAbRequestBody();
            inValue.Body.codDes = codDes;
            inValue.Body.nomDes = nomDes;
            Proyecto2.WSp2.insertarAbResponse retVal = ((Proyecto2.WSp2.proyectoWSSoap)(this)).insertarAb(inValue);
        }
        
        public void graficarAb() {
            base.Channel.graficarAb();
        }
        
        public void graficarAbDest() {
            base.Channel.graficarAbDest();
        }
        
        public void graficarAbOrig() {
            base.Channel.graficarAbOrig();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.WSp2.IngresarHashResponse Proyecto2.WSp2.proyectoWSSoap.IngresarHash(Proyecto2.WSp2.IngresarHashRequest request) {
            return base.Channel.IngresarHash(request);
        }
        
        public void IngresarHash(string nombre, int reser, float cost, float time) {
            Proyecto2.WSp2.IngresarHashRequest inValue = new Proyecto2.WSp2.IngresarHashRequest();
            inValue.Body = new Proyecto2.WSp2.IngresarHashRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.reser = reser;
            inValue.Body.cost = cost;
            inValue.Body.time = time;
            Proyecto2.WSp2.IngresarHashResponse retVal = ((Proyecto2.WSp2.proyectoWSSoap)(this)).IngresarHash(inValue);
        }
        
        public void graficarHash() {
            base.Channel.graficarHash();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.WSp2.buscarClaveHashResponse Proyecto2.WSp2.proyectoWSSoap.buscarClaveHash(Proyecto2.WSp2.buscarClaveHashRequest request) {
            return base.Channel.buscarClaveHash(request);
        }
        
        public int buscarClaveHash(string nombre) {
            Proyecto2.WSp2.buscarClaveHashRequest inValue = new Proyecto2.WSp2.buscarClaveHashRequest();
            inValue.Body = new Proyecto2.WSp2.buscarClaveHashRequestBody();
            inValue.Body.nombre = nombre;
            Proyecto2.WSp2.buscarClaveHashResponse retVal = ((Proyecto2.WSp2.proyectoWSSoap)(this)).buscarClaveHash(inValue);
            return retVal.Body.buscarClaveHashResult;
        }
        
        public void insertarVuelo(int clave, int cod) {
            base.Channel.insertarVuelo(clave, cod);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.WSp2.insertarAbdmResponse Proyecto2.WSp2.proyectoWSSoap.insertarAbdm(Proyecto2.WSp2.insertarAbdmRequest request) {
            return base.Channel.insertarAbdm(request);
        }
        
        public void insertarAbdm(int codDes, string nomDes) {
            Proyecto2.WSp2.insertarAbdmRequest inValue = new Proyecto2.WSp2.insertarAbdmRequest();
            inValue.Body = new Proyecto2.WSp2.insertarAbdmRequestBody();
            inValue.Body.codDes = codDes;
            inValue.Body.nomDes = nomDes;
            Proyecto2.WSp2.insertarAbdmResponse retVal = ((Proyecto2.WSp2.proyectoWSSoap)(this)).insertarAbdm(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.WSp2.insertarAbomResponse Proyecto2.WSp2.proyectoWSSoap.insertarAbom(Proyecto2.WSp2.insertarAbomRequest request) {
            return base.Channel.insertarAbom(request);
        }
        
        public void insertarAbom(int codDes, string nomDes) {
            Proyecto2.WSp2.insertarAbomRequest inValue = new Proyecto2.WSp2.insertarAbomRequest();
            inValue.Body = new Proyecto2.WSp2.insertarAbomRequestBody();
            inValue.Body.codDes = codDes;
            inValue.Body.nomDes = nomDes;
            Proyecto2.WSp2.insertarAbomResponse retVal = ((Proyecto2.WSp2.proyectoWSSoap)(this)).insertarAbom(inValue);
        }
        
        public bool busquedaABD(int numero) {
            return base.Channel.busquedaABD(numero);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.WSp2.recorrerColResponse Proyecto2.WSp2.proyectoWSSoap.recorrerCol(Proyecto2.WSp2.recorrerColRequest request) {
            return base.Channel.recorrerCol(request);
        }
        
        public string recorrerCol() {
            Proyecto2.WSp2.recorrerColRequest inValue = new Proyecto2.WSp2.recorrerColRequest();
            inValue.Body = new Proyecto2.WSp2.recorrerColRequestBody();
            Proyecto2.WSp2.recorrerColResponse retVal = ((Proyecto2.WSp2.proyectoWSSoap)(this)).recorrerCol(inValue);
            return retVal.Body.recorrerColResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proyecto2.WSp2.recorrerFilResponse Proyecto2.WSp2.proyectoWSSoap.recorrerFil(Proyecto2.WSp2.recorrerFilRequest request) {
            return base.Channel.recorrerFil(request);
        }
        
        public string recorrerFil() {
            Proyecto2.WSp2.recorrerFilRequest inValue = new Proyecto2.WSp2.recorrerFilRequest();
            inValue.Body = new Proyecto2.WSp2.recorrerFilRequestBody();
            Proyecto2.WSp2.recorrerFilResponse retVal = ((Proyecto2.WSp2.proyectoWSSoap)(this)).recorrerFil(inValue);
            return retVal.Body.recorrerFilResult;
        }
        
        public void eliminarMatriz(int PrimerPais, int SegundoPais) {
            base.Channel.eliminarMatriz(PrimerPais, SegundoPais);
        }
        
        public void modificarMatriz(int PrimerPais, int SegundoPais, double costo, int tiempo) {
            base.Channel.modificarMatriz(PrimerPais, SegundoPais, costo, tiempo);
        }
        
        public void graficarGrafo() {
            base.Channel.graficarGrafo();
        }
    }
}
